export const REDUX_STORAGE_LOAD = 'REDUX_STORAGE_LOAD';
export const ROUTER_LOCATION_CHANGE = '@@router/LOCATION_CHANGE';

export const USER_LOGIN_REQUESTED = 'USER_LOGIN_REQUESTED';
export const USER_LOGIN_SUCCEEDED = 'USER_LOGIN_SUCCEEDED';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const USER_LOGOUT_REQUESTED = 'USER_LOGOUT_REQUESTED';
export const USER_LOGOUT_SUCCEEDED = 'USER_LOGOUT_SUCCEEDED';
export const USER_LOGOUT_FAILED = 'USER_LOGOUT_FAILED';
export const USER_UPDATE_POSITION_REQUESTED = 'USER_UPDATE_POSITION_REQUESTED';
export const USER_UPDATE_POSITION_SUCCEEDED = 'USER_UPDATE_POSITION_SUCCEEDED';
export const USER_UPDATE_POSITION_FAILED = 'USER_UPDATE_POSITION_FAILED';
export const USER_FETCH_REQUESTED = 'USER_FETCH_REQUESTED';
export const USER_FETCH_SUCCEEDED = 'USER_FETCH_SUCCEEDED';
export const USER_FETCH_FAILED = 'USER_FETCH_FAILED';

export const SEARCH_TOPICS_REQUESTED = 'SEARCH_TOPICS_REQUESTED';
export const SEARCH_TOPICS_SUCCEEDED = 'SEARCH_TOPICS_SUCCEEDED';
export const SEARCH_TOPICS_FAILED = 'SEARCH_TOPICS_FAILED';
export const SEARCH_EMPTY_RESULTS = 'SEARCH_EMPTY_RESULTS';

export const TOPIC_CREATE_REQUESTED = 'TOPIC_CREATE_REQUESTED';
export const TOPIC_CREATE_SUCCEEDED = 'TOPIC_CREATE_SUCCEEDED';
export const TOPIC_CREATE_FAILED = 'TOPIC_CREATE_FAILED';
export const TOPIC_FETCH_REQUESTED = 'TOPIC_FETCH_REQUESTED';
export const TOPIC_FETCH_SUCCEEDED = 'TOPIC_FETCH_SUCCEEDED';
export const TOPIC_FETCH_FAILED = 'TOPIC_FETCH_FAILED';
export const TOPIC_DO_CHECKIN_REQUESTED = 'TOPIC_DO_CHECKIN_REQUESTED';
export const TOPIC_DO_CHECKIN_SUCCEEDED = 'TOPIC_DO_CHECKIN_SUCCEEDED';
export const TOPIC_DO_CHECKIN_FAILED = 'TOPIC_DO_CHECKIN_FAILED';
export const TOPIC_UNDO_CHECKIN_REQUESTED = 'TOPIC_UNDO_CHECKIN_REQUESTED';
export const TOPIC_UNDO_CHECKIN_SUCCEEDED = 'TOPIC_UNDO_CHECKIN_SUCCEEDED';
export const TOPIC_UNDO_CHECKIN_FAILED = 'TOPIC_UNDO_CHECKIN_FAILED';

// List of actions that act on persistent data
export const persistActionTypes = [
  USER_LOGIN_SUCCEEDED,
  USER_LOGOUT_SUCCEEDED,
  USER_FETCH_SUCCEEDED
];
